--------------------------------------------------------
--  파일이 생성됨 - 목요일-2월-23-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ANONYBOARD
--------------------------------------------------------

  CREATE TABLE "MINI"."ANONYBOARD" 
   (	"A_ID" NUMBER(5,0), 
	"A_DATE" DATE DEFAULT sysdate, 
	"A_TITLE" VARCHAR2(60), 
	"A_BODY" VARCHAR2(900), 
	"U_ID" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ANONYCOMM
--------------------------------------------------------

  CREATE TABLE "MINI"."ANONYCOMM" 
   (	"AC_DATE" DATE, 
	"AC_BODY" VARCHAR2(300), 
	"U_ID" VARCHAR2(30), 
	"AC_ID" NUMBER(5,0), 
	"A_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table RECIPE
--------------------------------------------------------

  CREATE TABLE "MINI"."RECIPE" 
   (	"R_ID" NUMBER(5,0), 
	"R_DATE" DATE DEFAULT sysdate, 
	"R_TITLE" VARCHAR2(60), 
	"R_BODY" VARCHAR2(1200), 
	"U_ID" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table RECIPELIKE
--------------------------------------------------------

  CREATE TABLE "MINI"."RECIPELIKE" 
   (	"R_ID" NUMBER(5,0), 
	"U_ID" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "MINI"."STORE" 
   (	"S_ID" NUMBER(5,0), 
	"S_NAME" VARCHAR2(50), 
	"S_KIND" VARCHAR2(20), 
	"S_MENU" VARCHAR2(100), 
	"S_MONEY" VARCHAR2(50), 
	"S_LOCATION" VARCHAR2(15), 
	"S_POINT" NUMBER(4,0), 
	"U_ID" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table SUGGEST
--------------------------------------------------------

  CREATE TABLE "MINI"."SUGGEST" 
   (	"SU_ID" NUMBER(5,0), 
	"SU_DATE" DATE DEFAULT sysdate, 
	"SU_KIND" CHAR(6), 
	"SU_TITLE" VARCHAR2(30), 
	"SU_BODY" VARCHAR2(255), 
	"U_ID" VARCHAR2(30)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table SUGGESTCOMM
--------------------------------------------------------

  CREATE TABLE "MINI"."SUGGESTCOMM" 
   (	"SUC_BODY" VARCHAR2(100), 
	"U_ID" VARCHAR2(30), 
	"SU_ID" NUMBER(5,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MINI"."USERS" 
   (	"U_ID" VARCHAR2(30), 
	"U_PW" VARCHAR2(30), 
	"U_NAME" VARCHAR2(50), 
	"U_MAIL" VARCHAR2(50), 
	"U_DATE" DATE DEFAULT sysdate, 
	"U_GRADE" CHAR(1) DEFAULT 'e', 
	"U_ATTEND" NUMBER(5,0) DEFAULT 0, 
	"U_POST" NUMBER(10,0) DEFAULT 0, 
	"U_COMMENT" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into MINI.ANONYBOARD
SET DEFINE OFF;
REM INSERTING into MINI.ANONYCOMM
SET DEFINE OFF;
REM INSERTING into MINI.RECIPE
SET DEFINE OFF;
REM INSERTING into MINI.RECIPELIKE
SET DEFINE OFF;
REM INSERTING into MINI.STORE
SET DEFINE OFF;
REM INSERTING into MINI.SUGGEST
SET DEFINE OFF;
REM INSERTING into MINI.SUGGESTCOMM
SET DEFINE OFF;
REM INSERTING into MINI.USERS
SET DEFINE OFF;
Insert into MINI.USERS (U_ID,U_PW,U_NAME,U_MAIL,U_DATE,U_GRADE,U_ATTEND,U_POST,U_COMMENT) values ('system','system','관리자','manager@board.com',to_date('23/01/01','RR/MM/DD'),'a',0,0,0);
Insert into MINI.USERS (U_ID,U_PW,U_NAME,U_MAIL,U_DATE,U_GRADE,U_ATTEND,U_POST,U_COMMENT) values ('yedam01','yedam001','예담학생','yyy@yedam.com',to_date('23/02/22','RR/MM/DD'),'e',0,0,0);
Insert into MINI.USERS (U_ID,U_PW,U_NAME,U_MAIL,U_DATE,U_GRADE,U_ATTEND,U_POST,U_COMMENT) values ('user1','user1','착한유저','chack@naver.com',to_date('23/02/22','RR/MM/DD'),'e',0,0,0);
--------------------------------------------------------
--  DDL for Index SYS_C007211
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007211" ON "MINI"."USERS" ("U_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007217
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007217" ON "MINI"."STORE" ("S_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007222
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007222" ON "MINI"."ANONYBOARD" ("A_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007227
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007227" ON "MINI"."ANONYCOMM" ("AC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007233
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007233" ON "MINI"."SUGGEST" ("SU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007238
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007238" ON "MINI"."RECIPE" ("R_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007222
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007222" ON "MINI"."ANONYBOARD" ("A_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007227
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007227" ON "MINI"."ANONYCOMM" ("AC_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007238
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007238" ON "MINI"."RECIPE" ("R_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007217
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007217" ON "MINI"."STORE" ("S_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007233
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007233" ON "MINI"."SUGGEST" ("SU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007211
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007211" ON "MINI"."USERS" ("U_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table ANONYBOARD
--------------------------------------------------------

  ALTER TABLE "MINI"."ANONYBOARD" ADD PRIMARY KEY ("A_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MINI"."ANONYBOARD" MODIFY ("U_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."ANONYBOARD" MODIFY ("A_BODY" NOT NULL ENABLE)
  ALTER TABLE "MINI"."ANONYBOARD" MODIFY ("A_TITLE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table ANONYCOMM
--------------------------------------------------------

  ALTER TABLE "MINI"."ANONYCOMM" ADD UNIQUE ("AC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MINI"."ANONYCOMM" MODIFY ("A_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."ANONYCOMM" MODIFY ("U_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."ANONYCOMM" MODIFY ("AC_BODY" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table RECIPE
--------------------------------------------------------

  ALTER TABLE "MINI"."RECIPE" ADD PRIMARY KEY ("R_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MINI"."RECIPE" MODIFY ("U_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."RECIPE" MODIFY ("R_BODY" NOT NULL ENABLE)
  ALTER TABLE "MINI"."RECIPE" MODIFY ("R_TITLE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table RECIPELIKE
--------------------------------------------------------

  ALTER TABLE "MINI"."RECIPELIKE" MODIFY ("U_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."RECIPELIKE" MODIFY ("R_ID" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "MINI"."STORE" ADD PRIMARY KEY ("S_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MINI"."STORE" MODIFY ("U_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."STORE" MODIFY ("S_POINT" NOT NULL ENABLE)
  ALTER TABLE "MINI"."STORE" MODIFY ("S_LOCATION" NOT NULL ENABLE)
  ALTER TABLE "MINI"."STORE" MODIFY ("S_KIND" NOT NULL ENABLE)
  ALTER TABLE "MINI"."STORE" MODIFY ("S_NAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table SUGGEST
--------------------------------------------------------

  ALTER TABLE "MINI"."SUGGEST" ADD PRIMARY KEY ("SU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MINI"."SUGGEST" MODIFY ("U_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."SUGGEST" MODIFY ("SU_BODY" NOT NULL ENABLE)
  ALTER TABLE "MINI"."SUGGEST" MODIFY ("SU_TITLE" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table SUGGESTCOMM
--------------------------------------------------------

  ALTER TABLE "MINI"."SUGGESTCOMM" MODIFY ("SU_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."SUGGESTCOMM" MODIFY ("U_ID" NOT NULL ENABLE)
  ALTER TABLE "MINI"."SUGGESTCOMM" MODIFY ("SUC_BODY" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MINI"."USERS" ADD PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MINI"."USERS" MODIFY ("U_MAIL" NOT NULL ENABLE)
  ALTER TABLE "MINI"."USERS" MODIFY ("U_NAME" NOT NULL ENABLE)
  ALTER TABLE "MINI"."USERS" MODIFY ("U_PW" NOT NULL ENABLE)
--------------------------------------------------------
--  Ref Constraints for Table ANONYBOARD
--------------------------------------------------------

  ALTER TABLE "MINI"."ANONYBOARD" ADD CONSTRAINT "U_ID2_FK" FOREIGN KEY ("U_ID")
	  REFERENCES "MINI"."USERS" ("U_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ANONYCOMM
--------------------------------------------------------

  ALTER TABLE "MINI"."ANONYCOMM" ADD CONSTRAINT "A_ID_FK" FOREIGN KEY ("A_ID")
	  REFERENCES "MINI"."ANONYBOARD" ("A_ID") ENABLE
  ALTER TABLE "MINI"."ANONYCOMM" ADD CONSTRAINT "U_ID3_FK" FOREIGN KEY ("U_ID")
	  REFERENCES "MINI"."USERS" ("U_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table RECIPE
--------------------------------------------------------

  ALTER TABLE "MINI"."RECIPE" ADD CONSTRAINT "U_ID6_FK" FOREIGN KEY ("U_ID")
	  REFERENCES "MINI"."USERS" ("U_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table RECIPELIKE
--------------------------------------------------------

  ALTER TABLE "MINI"."RECIPELIKE" ADD CONSTRAINT "R_ID_FK" FOREIGN KEY ("R_ID")
	  REFERENCES "MINI"."RECIPE" ("R_ID") ENABLE
  ALTER TABLE "MINI"."RECIPELIKE" ADD CONSTRAINT "U_ID7_FK" FOREIGN KEY ("U_ID")
	  REFERENCES "MINI"."USERS" ("U_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table STORE
--------------------------------------------------------

  ALTER TABLE "MINI"."STORE" ADD CONSTRAINT "U_ID_FK" FOREIGN KEY ("U_ID")
	  REFERENCES "MINI"."USERS" ("U_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table SUGGEST
--------------------------------------------------------

  ALTER TABLE "MINI"."SUGGEST" ADD CONSTRAINT "U_ID4_FK" FOREIGN KEY ("U_ID")
	  REFERENCES "MINI"."USERS" ("U_ID") ENABLE
--------------------------------------------------------
--  Ref Constraints for Table SUGGESTCOMM
--------------------------------------------------------

  ALTER TABLE "MINI"."SUGGESTCOMM" ADD CONSTRAINT "SU_ID_FK" FOREIGN KEY ("SU_ID")
	  REFERENCES "MINI"."SUGGEST" ("SU_ID") ENABLE
  ALTER TABLE "MINI"."SUGGESTCOMM" ADD CONSTRAINT "U_ID5_FK" FOREIGN KEY ("U_ID")
	  REFERENCES "MINI"."USERS" ("U_ID") ENABLE
