--------------------------------------------------------
--  파일이 생성됨 - 수요일-2월-22-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "MINI"."USERS" 
   (	"U_ID" VARCHAR2(30), 
	"U_PW" VARCHAR2(30), 
	"U_NAME" VARCHAR2(50), 
	"U_MAIL" VARCHAR2(50), 
	"U_DATE" DATE DEFAULT sysdate, 
	"U_GRADE" CHAR(1) DEFAULT 'e', 
	"U_ATTEND" NUMBER(5,0) DEFAULT 0, 
	"U_POST" NUMBER(10,0) DEFAULT 0, 
	"U_COMMENT" NUMBER(10,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into MINI.USERS
SET DEFINE OFF;
Insert into MINI.USERS (U_ID,U_PW,U_NAME,U_MAIL,U_DATE,U_GRADE,U_ATTEND,U_POST,U_COMMENT) values ('system','system','관리자','manager@board.com',to_date('23/01/01','RR/MM/DD'),'a',0,0,0);
Insert into MINI.USERS (U_ID,U_PW,U_NAME,U_MAIL,U_DATE,U_GRADE,U_ATTEND,U_POST,U_COMMENT) values ('yedam01','yedam01','예담학생','yyy@yedam.com',to_date('23/02/22','RR/MM/DD'),'e',0,0,0);
Insert into MINI.USERS (U_ID,U_PW,U_NAME,U_MAIL,U_DATE,U_GRADE,U_ATTEND,U_POST,U_COMMENT) values ('user1','user1','착한유저','chack@naver.com',to_date('23/02/22','RR/MM/DD'),'e',0,0,0);
--------------------------------------------------------
--  DDL for Index SYS_C007211
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007211" ON "MINI"."USERS" ("U_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007211
--------------------------------------------------------

  CREATE UNIQUE INDEX "MINI"."SYS_C007211" ON "MINI"."USERS" ("U_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "MINI"."USERS" ADD PRIMARY KEY ("U_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "MINI"."USERS" MODIFY ("U_MAIL" NOT NULL ENABLE)
  ALTER TABLE "MINI"."USERS" MODIFY ("U_NAME" NOT NULL ENABLE)
  ALTER TABLE "MINI"."USERS" MODIFY ("U_PW" NOT NULL ENABLE)
