--------------------------------------------------------
--  DDL for Sequence REPLY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."REPLY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "HR"."PRODUCT" 
   (	"PRODUCT_CODE" VARCHAR2(10 BYTE), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"ORIGIN_PRICE" NUMBER, 
	"SALE_PRICE" NUMBER, 
	"PRODUCT_DESC" VARCHAR2(1000 BYTE), 
	"LIKE_IT" NUMBER(3,1), 
	"IMAGE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT_REPLY
--------------------------------------------------------

  CREATE TABLE "HR"."PRODUCT_REPLY" 
   (	"REPLY_NO" NUMBER, 
	"REPLY_WRITER" VARCHAR2(100 BYTE), 
	"REPLY_CONTENT" VARCHAR2(100 BYTE), 
	"REPLY_DATE" DATE DEFAULT sysdate, 
	"PRODUCT_CODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FULL_CALENDER
--------------------------------------------------------

  CREATE TABLE "HR"."FULL_CALENDER" 
   (	"TITLE" VARCHAR2(100 BYTE), 
	"START_DATE" VARCHAR2(20 BYTE), 
	"END_DATE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBERS
--------------------------------------------------------

  CREATE TABLE "HR"."MEMBERS" 
   (	"ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"PASSWD" VARCHAR2(10 BYTE), 
	"MAIL" VARCHAR2(30 BYTE), 
	"AUTH" VARCHAR2(10 BYTE) DEFAULT 'User'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.PRODUCT
SET DEFINE OFF;
Insert into HR.PRODUCT (PRODUCT_CODE,PRODUCT_NAME,ORIGIN_PRICE,SALE_PRICE,PRODUCT_DESC,LIKE_IT,IMAGE) values ('CF0001','과테말라 안티구아',5000,4500,'과테말라 안티구아 커피입니다',4.5,'과테말라 안티구아.jpg');
Insert into HR.PRODUCT (PRODUCT_CODE,PRODUCT_NAME,ORIGIN_PRICE,SALE_PRICE,PRODUCT_DESC,LIKE_IT,IMAGE) values ('CF0002','니카라구아 더치원두',6000,5400,'니카라구아 더치원두입니다',3.5,'니카라구아 더치.jpg');
Insert into HR.PRODUCT (PRODUCT_CODE,PRODUCT_NAME,ORIGIN_PRICE,SALE_PRICE,PRODUCT_DESC,LIKE_IT,IMAGE) values ('CF0003','브라질 산토스',5300,4800,'브라질 산토스 커피입니다',4.5,'브라질산토스.jpg');
Insert into HR.PRODUCT (PRODUCT_CODE,PRODUCT_NAME,ORIGIN_PRICE,SALE_PRICE,PRODUCT_DESC,LIKE_IT,IMAGE) values ('CF0004','에티오피아 예가체프',5500,5000,'에티오피아 예가체프 커피입니다',4,'에티오피아 예가체프.jpg');
Insert into HR.PRODUCT (PRODUCT_CODE,PRODUCT_NAME,ORIGIN_PRICE,SALE_PRICE,PRODUCT_DESC,LIKE_IT,IMAGE) values ('CF0005','케냐 오크라톡신',5800,5300,'케냐 오크라톡신 커피입니다',3,'케냐 오크라톡신.jpg');
Insert into HR.PRODUCT (PRODUCT_CODE,PRODUCT_NAME,ORIGIN_PRICE,SALE_PRICE,PRODUCT_DESC,LIKE_IT,IMAGE) values ('CF0006','코스타리카 따라주',6500,6000,'코스타리카 따라주 커피입니다',5,'코스타리카 따라주.jpg');
REM INSERTING into HR.PRODUCT_REPLY
SET DEFINE OFF;
Insert into HR.PRODUCT_REPLY (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DATE,PRODUCT_CODE) values (12,'user02','brazil coffee is the best',to_date('23/03/29','RR/MM/DD'),'CF0001');
Insert into HR.PRODUCT_REPLY (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DATE,PRODUCT_CODE) values (8,'user02','??¤????°?',to_date('23/03/28','RR/MM/DD'),'CF0001');
Insert into HR.PRODUCT_REPLY (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DATE,PRODUCT_CODE) values (6,'user01','123123123',to_date('23/03/28','RR/MM/DD'),'CF0001');
Insert into HR.PRODUCT_REPLY (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DATE,PRODUCT_CODE) values (9,'user02','hihihiyoyo111',to_date('23/03/28','RR/MM/DD'),'CF0001');
Insert into HR.PRODUCT_REPLY (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DATE,PRODUCT_CODE) values (10,'user02','test111',to_date('23/03/28','RR/MM/DD'),'CF0001');
Insert into HR.PRODUCT_REPLY (REPLY_NO,REPLY_WRITER,REPLY_CONTENT,REPLY_DATE,PRODUCT_CODE) values (11,'user02','no test',to_date('23/03/28','RR/MM/DD'),'CF0001');
REM INSERTING into HR.FULL_CALENDER
SET DEFINE OFF;
Insert into HR.FULL_CALENDER (TITLE,START_DATE,END_DATE) values ('다정생일','2023-03-16',null);
Insert into HR.FULL_CALENDER (TITLE,START_DATE,END_DATE) values ('자바스터디','2023-03-30T18:00:00','2023-03-30T20:00:00');
Insert into HR.FULL_CALENDER (TITLE,START_DATE,END_DATE) values ('여행','2023-03-31','2023-04-03');
REM INSERTING into HR.MEMBERS
SET DEFINE OFF;
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user1','사용자1','1111','user1@email','User');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user2','사용자2','1111','user2@email','User');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user3','사용자3','1111','user3@email','User');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('admin','운영자','1111','asdfg','Admin');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user6','사용자6','1111','user6@email','User');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user4','사용자4','1111','user4@email','User');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user7','사용자7','1111','user7@email','User');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user5','사용자5','1111','user5@email','User');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user9','사용자9','1111','user9@email','User');
Insert into HR.MEMBERS (ID,NAME,PASSWD,MAIL,AUTH) values ('user8','사용자8','1111','user8@email','User');
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "HR"."PRODUCT" ADD PRIMARY KEY ("PRODUCT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PRODUCT" MODIFY ("LIKE_IT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUCT" MODIFY ("PRODUCT_DESC" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUCT" MODIFY ("ORIGIN_PRICE" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT_REPLY
--------------------------------------------------------

  ALTER TABLE "HR"."PRODUCT_REPLY" ADD PRIMARY KEY ("REPLY_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."PRODUCT_REPLY" MODIFY ("REPLY_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "HR"."PRODUCT_REPLY" MODIFY ("REPLY_WRITER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FULL_CALENDER
--------------------------------------------------------

  ALTER TABLE "HR"."FULL_CALENDER" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HR"."FULL_CALENDER" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBERS" MODIFY ("AUTH" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBERS" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "HR"."MEMBERS" MODIFY ("NAME" NOT NULL ENABLE);
  
  
  drop table members;

  CREATE TABLE "HR"."MEMBERS" 
   (   "MEMBER_ID" VARCHAR2(20 BYTE), 
   "MEMBER_NAME" VARCHAR2(200 BYTE), 
   "MEMBER_TEL" VARCHAR2(20 BYTE), 
   "MEMBER_ADDR" VARCHAR2(100 BYTE), 
   "MEMBER_PW" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HR.MEMBERS
SET DEFINE OFF;
Insert into HR.MEMBERS (MEMBER_ID,MEMBER_NAME,MEMBER_TEL,MEMBER_ADDR,MEMBER_PW) values ('user01','사용자1','010-1111-1111','대구 100번지','1111');
Insert into HR.MEMBERS (MEMBER_ID,MEMBER_NAME,MEMBER_TEL,MEMBER_ADDR,MEMBER_PW) values ('user02','사용자2','010-2222-2222','대구 200번지','1111');
Insert into HR.MEMBERS (MEMBER_ID,MEMBER_NAME,MEMBER_TEL,MEMBER_ADDR,MEMBER_PW) values ('user03','사용자3','010-3333-3333','대구 300번지','1111');
Insert into HR.MEMBERS (MEMBER_ID,MEMBER_NAME,MEMBER_TEL,MEMBER_ADDR,MEMBER_PW) values ('user04','사용자4','010-4444-4444','대구 400번지','1111');
Insert into HR.MEMBERS (MEMBER_ID,MEMBER_NAME,MEMBER_TEL,MEMBER_ADDR,MEMBER_PW) values ('user05','사용자5','010-5555-5555','대구 500번지','1111');
Insert into HR.MEMBERS (MEMBER_ID,MEMBER_NAME,MEMBER_TEL,MEMBER_ADDR,MEMBER_PW) values ('user06','사용자6','010-6666-6666','대구 600번지','1111');
--------------------------------------------------------
--  Constraints for Table MEMBERS
--------------------------------------------------------

  ALTER TABLE "HR"."MEMBERS" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."MEMBERS" MODIFY ("MEMBER_NAME" NOT NULL ENABLE);
